name: alexandrakinter
favicon: null
layout_spectrum: 0.532111688517034
typography_spectrum: 0.0968832594808191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8576742452569306
  lightness: 0.7449180285912007
  saturation: 0.8472141039092094
  rhythmicContrast: 0.4687624538782984
purpose: []
